name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Package and Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Upgrade pip and install conan
        run: python -m pip install --upgrade pip conan

      - name: Add remote
        run: conan remote add tarc https://api.bintray.com/conan/tarc/tarc

      - name: Log on
        run: conan user -p $APIKEY -r tarc tarc
        env:
          APIKEY: ${{ secrets.APIKEY }}

      - name: Create
        run: conan create . -pr default -pr ./release.profile -pr cxx11abi.profile
        shell: bash

      - name: Publish
        run: conan upload library-template/1.0.0 -r tarc --all --confirm
        shell: bash
