name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Package and Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Upgrade pip and install conan
        run: python -m pip install --upgrade pip conan gitpython

      - name: Add remote
        run: conan remote add tarc https://api.bintray.com/conan/tarc/tarc

      - name: Log on
        run: conan user -p $APIKEY -r tarc tarc
        env:
          APIKEY: ${{ secrets.APIKEY }}

      - name: Set version tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Show version tag
        run: echo $GIT_TAG
        env:
          GIT_TAG: ${{ steps.vars.outputs.tag }}

      - name: Create
        run: conan create . -pr default -pr ./profiles/release.profile -pr ./profiles/cxx11abi.profile ./profiles/cxx17.profile
        env:
          GIT_TAG: ${{ steps.vars.outputs.tag }}
        shell: bash

      - name: Publish
        run: conan upload library-template/* -r tarc --all --confirm
        shell: bash
