name: Build and Unit Test

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*

  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Step by Step (MacOS and Ubuntu)

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        platform: [x64, x86]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Upgrade pip and install conan
        run: python -m pip install --upgrade pip conan

      - name: Install
        run: ./install.sh
        shell: bash

      - name: Build
        run: ./build.sh
        shell: bash

      - name: Package
        run: ./package.sh
        shell: bash

      - name: Export Package
        run: ./export-pkg.sh
        shell: bash
